# Autogenerated by nbdev

d = { 'settings': { 'branch': 'testing-nbdev',
                'doc_baseurl': '/test-repo',
                'doc_host': 'https://farahalfawzy.github.io',
                'git_url': 'https://github.com/farahalfawzy/test-repo',
                'lib_path': 'test_repo'},
  'syms': {'test_repo.core': {'test_repo.core.foo': ('core.html#foo', 'test_repo/core.py')}}}
